name: CI

on:
  push:
    branches: [ release ]

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js (12.16.2)
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'

    - name: Install Pacakges 
      run: npm ci
      
    - name: Build Step 
      env: 
        CI: "" 
      run: npm run build

    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }} 
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
        publish_dir: ./build
